name: Gluestack CLI Test

on:
  push:
    branches:
      - patch
  pull_request:
    branches:
      - patch

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        package-manager: [npm, yarn, pnpm, bun]

    runs-on: ${{ matrix.os }}
    env:
      working-directory: packages/gluestack-cli
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Run tests
        run: yarn test packageManager=${{ matrix.package-manager }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: packages/gluestack-cli/junit.xml
